services:
  neo4j:
    image: neo4j:5.13
    container_name: neo4j-graph-rag
    ports:
      - "7474:7474"  # Neo4j Browser
      - "7687:7687"  # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "password", "RETURN 1"]
      interval: 10s
      timeout: 10s
      retries: 5

  streamlit-app:
    build: .
    container_name: streamlit-graph-rag
    ports:
      - "8501:8501"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      # LLM API Keys (optional - will use mock responses if not provided)
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - GROQ_API_KEY=${GROQ_API_KEY:-}
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY:-}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-}
    depends_on:
      neo4j:
        condition: service_healthy
    volumes:
      - .:/app
    command: streamlit run app.py --server.address 0.0.0.0 --server.port 8501

volumes:
  neo4j_data:
  neo4j_logs: